name: hexham_pint
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  responsive_builder: ^0.7.1
  entry: ^1.0.0
  get: ^4.6.6
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.1
  readmore: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home_images/
    - assets/images/hover_card_images/
    - assets/images/container3/
    - assets/images/container4/
  fonts:
    - family: David Libre
      fonts:
        - asset: assets/fonts/david-libre/DavidLibre-Regular.ttf
        - asset: assets/fonts/david-libre/DavidLibre-Medium.ttf
        - asset: assets/fonts/david-libre/DavidLibre-Bold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter/Inter_28pt-Bold.ttf
