# Deploy Flutter web app to Firebase Hosting
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Flutter with explicit version
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5" # Replace with the desired version

      # Step 3: Verify Flutter installation
      - name: Verify Flutter Installation
        run: flutter --version

      # Step 4: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Build the Flutter web app
      - name: Build Flutter Web App
        run: flutter build web --release

      # Step 6: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HIXHAM_PINT }}
          channelId: live
          projectId: hixham-pint
